In [1]:
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'


Tensor("Add:0", shape=(), dtype=float32)
11.0


In [14]:
# 实现加法运算
a = tf.constant(5.0)
b = tf.constant(6.0)
sum1 = tf.add(a, b)

# 张量的重载
val = 3
sum2 = a + val

# 默认这张图，相当于分配一段内存
graph = tf.get_default_graph() 

print(sum1)

# 开启一个会话，只能运行一个图结构
# config = tf.ConfigProto(log_device_placement = True) 可以查看程序在哪里进行运算，命令行显示
with tf.Session() as sess:
# 可以指定运行一个图，graph=g
# with tf.Session(graph = g) as sess:
    # print(sess.run(c))  # 跟着运行g图
    print(sess.run(sum1)) # 就run运行跟session有关系
    # sess.run()只能run定义的张量，不能run Python中的type
    print(sess.run([sum1, a, b])) # 使用列表run多个值
    print(sum1.eval())    # 只要由上下文交互环境，就可以使用eval
    print(sum2.eval())    # 张量也能重载
    print(a.graph)
    print(sum1.graph)
    print(sess.graph)

Tensor("Add_11:0", shape=(), dtype=float32)
11.0
[11.0, 5.0, 6.0]
11.0
8.0


In [10]:
# 图的创建
g = tf.Graph()

with g.as_default():
    c = tf.constant(11.0)
    print(c.graph)


In [24]:
# session的run()方法，配合placeholder实现，实时数据进行训练
plt = tf.placeholder(tf.float32, [None, 3]) # placeholder占位符，
with tf.Session() as sess:
    print(sess.run(plt, feed_dict={plt: [[1,2,3], [4,5,6]]})) # feed_dict字典
    print(sess.run(plt, feed_dict={plt: [[1,2,3], [4,5,6],[11,23,451]]}))
    print(sess.graph)
    print("shape of a: ", a.shape)
    print("shape of plt: ", plt.shape) # shape of tensor
    print("name of a", a.name) # name of tensor
    print(a.op) # content of op 

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
[[   1.    2.    3.]
 [   4.    5.    6.]
 [  11.   23.  451.]]
shape of a:  ()
shape of plt:  (?, 3)
name of a Const_22:0
name: "Const_22"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_FLOAT
      tensor_shape {
      }
      float_val: 5.0
    }
  }
}



In [32]:
# tensor reshape: static and dynamic
plt = tf.placeholder(tf.float32, [None, 2])
print(plt)
plt.set_shape([3,2]) # 用static性状固定后，就不能再set_shape()改变了
print(plt)
plt_reshape = tf.reshape(plt, [2,3]) #dynamic性状,用reshape可以改变static,注意元素个数不能变
print(plt_reshape)
with tf.Session() as sess:
    pass

Tensor("Placeholder_16:0", shape=(?, 2), dtype=float32)
Tensor("Placeholder_16:0", shape=(3, 2), dtype=float32)
Tensor("Reshape_2:0", shape=(2, 3), dtype=float32)


In [42]:
# change type of tensor  
a = tf.cast([[1,2,3],[4,5,6]],tf.float32)
with tf.Session() as sess:
    print(a.eval())
    print(a)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
Tensor("Cast_9:0", shape=(2, 3), dtype=float32)
