# numpy

In [20]:
import numpy as np
import random
# 生成数组
t1 = np.arange(10)
print("t1 =", t1)
print("t1.dtype =", t1.dtype)
# 按数据类型新建数组
t2 = np.array([0,1,1,0], dtype=bool)
print("t2 =", t2)
# 修改数组数据类型
t3 = t2.astype("int8")
print("t3 =", t3, t3.dtype)
# 生成随机小数
t4 = np.array([random.random() for i in range(10)]) 
print("t4 =", t4, t4.dtype)
# 保留小数位
t5 = np.round(t4, 2)
print("t5 =", t5)

t1 = [0 1 2 3 4 5 6 7 8 9]
t1.dtype = int64
t2 = [False  True  True False]
t3 = [0 1 1 0] int8
t4 = [ 0.22585758  0.9913583   0.62147531  0.04202961  0.63619583  0.71781337
  0.58213982  0.71346304  0.51479025  0.14770472] float64
t5 = [ 0.23  0.99  0.62  0.04  0.64  0.72  0.58  0.71  0.51  0.15]


# numpy加载数据文件csv

In [4]:
import numpy as np
# get file path
us_file_path = "/usr/python_ML/data_analysis/youtube_video_data/US_video_data_numbers.csv"
uk_file_path = "/usr/python_ML/data_analysis/youtube_video_data/GB_video_data_numbers.csv"
# get data from csv
us_data = np.loadtxt(us_file_path, delimiter=",", dtype="int")
uk_data = np.loadtxt(uk_file_path, delimiter=",", dtype="int")
print("t1 =\n", us_data)
print("t2 =\n", uk_data)
#
zeros_data = np.zeros((us_data.shape[0], 1)).astype(int)
ones_data = np.ones((uk_data.shape[0],1)).astype(int)
print(zeros_data, zeros_data.shape, us_data.shape)
us_data = np.hstack((us_data, zeros_data))
uk_data = np.hstack((uk_data, ones_data))
print("拼接后us_data =\n", us_data)
print("拼接后uk_data =\n", uk_data)
# 拼接两组数据
final_data = np.vstack((us_data, uk_data))
print("final_data =\n", final_data)

np.isnan(final_data).astype(int).sum()

t1 =
 [[4394029  320053    5931   46245]
 [7860119  185853   26679       0]
 [5845909  576597   39774  170708]
 ..., 
 [ 142463    4231     148     279]
 [2162240   41032    1384    4737]
 [ 515000   34727     195    4722]]
t2 =
 [[7426393   78240   13548     705]
 [ 494203    2651    1309       0]
 [ 142819   13119     151    1141]
 ..., 
 [ 109222    4840      35     212]
 [ 626223   22962     532    1559]
 [  99228    1699      23     135]]
[[0]
 [0]
 [0]
 ..., 
 [0]
 [0]
 [0]] (1688, 1) (1688, 4)
拼接后us_data =
 [[4394029  320053    5931   46245       0]
 [7860119  185853   26679       0       0]
 [5845909  576597   39774  170708       0]
 ..., 
 [ 142463    4231     148     279       0]
 [2162240   41032    1384    4737       0]
 [ 515000   34727     195    4722       0]]
拼接后uk_data =
 [[7426393   78240   13548     705       1]
 [ 494203    2651    1309       0       1]
 [ 142819   13119     151    1141       1]
 ..., 
 [ 109222    4840      35     212       1]
 [ 626223   22962    

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       ..., 
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])